document.writeln("<!DOCTYPE HTML>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<title>Ziyuan Jiang\'s Personal Website</title>");
document.writeln("		<meta charset=\'utf-8\' />");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width, initial-scale=1, user-scalable=no\' />");
document.writeln("		<link rel=\'stylesheet\' href=\'https://ziyuanjiang825.github.io/assets/css/main.css\' />");
document.writeln("	</head>");
document.writeln("	<body class=\'is-preload\'>");
document.writeln("								<header id=\'header\'>");
document.writeln("									<a href=\'index.html\' class=\'logo\'>Created by <strong>Ziyuan Jiang</strong></a>");
document.writeln("									<ul class=\'icons\'>");
document.writeln("										<li><a href=\'#\' class=\'icon brands fa-twitter\'><span class=\'label\'>Twitter</span></a></li>");
document.writeln("										<li><a href=\'https://www.facebook.com/jiang.ziyuan.98/\' class=\'icon brands fa-facebook-f\'><span class=\'label\'>Facebook</span></a></li>");
document.writeln("										<li><a href=\'#\' class=\'icon brands fa-weixin\'><span class=\'label\'>weixin</span></a></li>");
document.writeln("										<li><a href=\'#\' class=\'icon brands fa-instagram\'><span class=\'label\'>Instagram</span></a></li>");
document.writeln("										<li><a href=\'https://weibo.com/2831452755/profile?topnav=1&wvr=6\' class=\'icon brands fa-weibo\'><span class=\'label\'>Weibo</span></a></li>");
document.writeln("									</ul>");
document.writeln("								</header>");
document.writeln("");
document.writeln("		<!-- Scripts -->");
document.writeln("			<script src=\'https://ziyuanjiang825.github.io/assets/js/jquery.min.js\'></script>");
document.writeln("			<script src=\'https://ziyuanjiang825.github.io/assets/js/browser.min.js\'></script>");
document.writeln("			<script src=\'https://ziyuanjiang825.github.io/assets/js/breakpoints.min.js\'></script>");
document.writeln("			<script src=\'https://ziyuanjiang825.github.io/assets/js/util.js\'></script>");
document.writeln("			<script src=\'https://ziyuanjiang825.github.io/assets/js/main.js\'></script>");
document.writeln("");
document.writeln("	</body>");
document.writeln("</html>");