document.writeln("<!DOCTYPE HTML>");
document.writeln("<!--");
document.writeln("	Editorial by HTML5 UP");
document.writeln("	html5up.net | @ajlkn");
document.writeln("	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)");
document.writeln("-->");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<title>Ziyuan Jiang\'s Personal Website</title>");
document.writeln("		<meta charset=\'utf-8\' />");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width, initial-scale=1, user-scalable=no\' />");
document.writeln("		<link rel=\'stylesheet\' href=\'assets/css/main.css\' />");
document.writeln("	</head>");
document.writeln("	<body class=\'is-preload\'>");
document.writeln("					<!-- Search -->");
document.writeln("						<section id=\'search\' class=\'alt\'>");
document.writeln("							<form method=\'post\' action=\'#\'>");
document.writeln("								<input type=\'text\' name=\'query\' id=\'query\' placeholder=\'Search\' />");
document.writeln("							</form>");
document.writeln("						</section>");
document.writeln("");
document.writeln("					<!-- Menu -->");
document.writeln("						<nav id=\'menu\'>");
document.writeln("							<header class=\'major\'>");
document.writeln("								<h2>Menu</h2>");
document.writeln("							</header>");
document.writeln("							<ul>");
document.writeln("								<li><a href=\'index.html\'>Homepage</a></li>");
document.writeln("								<li>");
document.writeln("									<span class=\'opener\'>Undergraduate Thesis</span>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'#\'>Capacitance Bridge</a></li>");
document.writeln("										<li><a href=\'#\'>Impedance Analysis</a></li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li><a href=\'#\'>Publications</a></li>");
document.writeln("								<li><a href=\'#\'>With lele</a></li>");
document.writeln("								<li>");
document.writeln("									<span class=\'opener\'>Leetcode</span>");
document.writeln("									<ul>");
document.writeln("										<li>");
document.writeln("											<span class=\'opener\'>Algorithm</span>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'https://ziyuanjiang825.github.io/Leetcode/Algorithm/DP/dp_main.html\'>Dynamic Programming</a></li>");
document.writeln("												<li><a href=\'#\'>Divide and Conquer</a></li>");
document.writeln("												<li><a href=\'#\'>Search</a></li>");
document.writeln("												<li><a href=\'#\'>Greedy</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("										<li>");
document.writeln("											<span class=\'opener\'>Data Structure</span>");
document.writeln("											<ul>");
document.writeln("												<li><a href=\'#\'>Array</a></li>");
document.writeln("												<li><a href=\'#\'>String</a></li>");
document.writeln("												<li><a href=\'#\'>Heap</a></li>");
document.writeln("												<li><a href=\'#\'>Tree</a></li>");
document.writeln("												<li><a href=\'#\'>Hash Table</a></li>");
document.writeln("												<li><a href=\'#\'>Union Find</a></li>");
document.writeln("												<li><a href=\'#\'>Segment Tree</a></li>");
document.writeln("												<li><a href=\'#\'>Stack</a></li>");
document.writeln("												<li><a href=\'#\'>Queue</a></li>");
document.writeln("												<li><a href=\'#\'>Graph</a></li>");
document.writeln("												<li><a href=\'#\'>Pointer</a></li>");
document.writeln("											</ul>");
document.writeln("										</li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</nav>");
document.writeln("");
document.writeln("					<!-- Section -->");
document.writeln("						<section>");
document.writeln("							<header class=\'major\'>");
document.writeln("								<h2>Get in touch</h2>");
document.writeln("							</header>");
document.writeln("							<p>I am currently a senior student at Tsinghua University, majoring in automation. And I am also an incoming MSCS student at Columbia University starting in Fall 2021. Feel free to contact with me:)</p>");
document.writeln("							<ul class=\'contact\'>");
document.writeln("								<li class=\'icon solid fa-envelope\'><a href=\'#\'>ziyuanjiang17@gmail.com</a></li>");
document.writeln("								<li class=\'icon solid fa-phone\'>(86)18801233590</li>");
document.writeln("								<li class=\'icon solid fa-home\'>Tsinghua University<br />");
document.writeln("								Beijing, China 100084</li>");
document.writeln("							</ul>");
document.writeln("						</section>");
document.writeln("");
document.writeln("					<!-- Footer -->");
document.writeln("						<footer id=\'footer\'>");
document.writeln("							<p class=\'copyright\'>&copy; Ziyuan Jiang. All rights reserved. Design: <a href=\'https://html5up.net\'>HTML5 UP</a>.</p>");
document.writeln("						</footer>");
document.writeln("");
document.writeln("	</body>");
document.writeln("</html>");